import { OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { MnDatetimeServices } from './mn-datetime.services';
import { MnCalendarViewComponent } from './mn-calendar-view.component';
export declare const YEAR_MILLISECONDS = 864000;
export declare class MnCalendarComponent implements OnInit, OnChanges {
    private _mds;
    year: number;
    month: number;
    date: number;
    viewType: string;
    mode: string;
    minDate: any;
    maxDate: any;
    startDate: any;
    endDate: any;
    result: any;
    viewComponent: any;
    _viewComponent: MnCalendarViewComponent;
    _year: number;
    _month: number;
    _current: Date;
    _view: any;
    _show: any;
    minDate_: any;
    maxDate_: any;
    constructor(_mds: MnDatetimeServices);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    getPrevMonth(): any;
    _getPrevMonth: () => any;
    getPrevYear(): any;
    _getPrevYear: () => any;
    getNextMonth(): any;
    _getNextMonth: () => any;
    getNextYear(): any;
    _getNextYear: () => any;
    getView(e: any): void;
    _getView: (e: any) => void;
    getShow: any;
}
