/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './col.component';
const styles_ColComponent:any[] = ([] as any[]);
export const RenderType_ColComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_ColComponent,
    data:{}});
export function View_ColComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),i0.ɵncd((null as any),
      0),(_l()(),i0.ɵted((null as any),['\n    ']))],(null as any),(null as any));
}
export function View_ColComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'cols',([] as any[]),
      (null as any),(null as any),(null as any),View_ColComponent_0,RenderType_ColComponent)),
      i0.ɵdid(638976,(null as any),0,i1.ColComponent,[i0.ElementRef,i0.Renderer2],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ColComponentNgFactory:i0.ComponentFactory<i1.ColComponent> = i0.ɵccf('cols,[cols]',
    i1.ColComponent,View_ColComponent_Host_0,{gutter:'gutter',span:'span',order:'order'},
    {},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL01pemkvZ2l0L215LWFwcC9zcmMvbGliL2ZsZXgtbGF5b3V0L2NvbC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvTWl6aS9naXQvbXktYXBwL3NyYy9saWIvZmxleC1sYXlvdXQvY29sLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL01pemkvZ2l0L215LWFwcC9zcmMvbGliL2ZsZXgtbGF5b3V0L2NvbC5jb21wb25lbnQudHMuQ29sQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9NaXppL2dpdC9teS1hcHAvc3JjL2xpYi9mbGV4LWxheW91dC9jb2wuY29tcG9uZW50LnRzLkNvbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG4gICAgIiwiPGNvbHM+PC9jb2xzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLHNEQUNRO01BQUEsR0FBeUI7OztvQkNEakM7TUFBQTthQUFBO1VBQUE7SUFBQTs7Ozs7In0=
