/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './row.component';
const styles_RowComponent:any[] = ['[_nghost-%COMP%] {\n                display: flex;\n                flex-wrap: wrap;\n                align-items: stretch;\n                box-sizing: border-box;\n            }'];
export const RenderType_RowComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,styles:styles_RowComponent,
    data:{}});
export function View_RowComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵncd((null as any),0)],(null as any),(null as any));
}
export function View_RowComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'row',([] as any[]),
      (null as any),(null as any),(null as any),View_RowComponent_0,RenderType_RowComponent)),
      i0.ɵdid(4833280,(null as any),1,i1.RowComponent,[i0.ElementRef,i0.Renderer2],
          (null as any),(null as any)),i0.ɵqud(603979776,1,{colsArr:1})],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const RowComponentNgFactory:i0.ComponentFactory<i1.RowComponent> = i0.ɵccf('row, [row]',
    i1.RowComponent,View_RowComponent_Host_0,{gutter:'gutter'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL01pemkvZ2l0L215LWFwcC9zcmMvbGliL2ZsZXgtbGF5b3V0L3Jvdy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvTWl6aS9naXQvbXktYXBwL3NyYy9saWIvZmxleC1sYXlvdXQvcm93LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL01pemkvZ2l0L215LWFwcC9zcmMvbGliL2ZsZXgtbGF5b3V0L3Jvdy5jb21wb25lbnQudHMuUm93Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9NaXppL2dpdC9teS1hcHAvc3JjL2xpYi9mbGV4LWxheW91dC9yb3cuY29tcG9uZW50LnRzLlJvd0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxuZy1jb250ZW50PjwvbmctY29udGVudD4iLCI8cm93Pjwvcm93PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OzJCQ0FBOzs7b0JDQUE7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
